Models/ServiceProvider.cs
namespace HomeService
{
    public class ServiceProvider
    {
        public int id { get; set; } 
        public int serId { get; set; }
        public string name { get; set; }
        public string imgType { get; set; }
        public string img { get; set; }
        public string email {get;set;}
        public string about { get; set; }
        public string phone{get;set;}
        public string city { get; set; }
        public int cateId { get; set; }
        public string cateName{get;set;}
        public string location { get; set; }

    }
}

Controllers/ServiceProviderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;

namespace HomeService.Controllers
{
    public class ServiceProviderController:Controller
    {
        private MySqlCommand com {get;set;}
        private MySqlDataReader reader{get;set;}
        private MySqlDataAdapter dataAdapter{get;set;}
        private dbConnection con {get;set;}
        private ServiceProvider provider {get;set;}
        public IActionResult ServiceProviderDashbaord()
        {
            return View();
        }
        public IActionResult ServiceProviderProfile()
        {
            //GetProvider();
            return View();
        }

        public IActionResult EditService()
        {
            return View();
        }
        //SELECT serviceprovider.imgType,serviceprovider.img,serviceprovider.about,serviceprovider.city,servicecategories.name,serviceprovider.loaction,serviceprovider.userId FROM `serviceprovider`,servicecategories WHERE serviceprovider.cateId = servicecategories.id AND serviceprovider.userId = "+userId
        public IActionResult GetProvider()
        {
            try
            {
                int userId = Convert.ToInt16(HttpContext.Session.GetString("userId"));
                con = new dbConnection();
                string sqlQuery = "SELECT serviceprovider.imgType,serviceprovider.img,serviceprovider.about,serviceprovider.city,servicecategories.name,serviceprovider.loaction,serviceprovider.userId,servicecategories.id FROM `serviceprovider`,servicecategories WHERE serviceprovider.cateId = servicecategories.id AND serviceprovider.userId = "+userId;
                dataAdapter = new MySqlDataAdapter(sqlQuery,con.connection);
                DataTable data = new DataTable();
                dataAdapter.Fill(data);
                provider = new ServiceProvider();
                DataRow row = data.Rows[0];
                provider.img = row[0].ToString()+","+Convert.ToBase64String((byte[])row[1]);
                provider.about = row[2].ToString();
                provider.city = row[3].ToString();
                provider.cateName = row[4].ToString();
                provider.location = row[5].ToString();
                provider.serId = int.Parse(row[6].ToString());
                provider.cateId = int.Parse(row[7].ToString());
                
            }
            catch(Exception ex){throw(ex);}
            return Ok(provider);
        }
        private ServiceCategroy categroy{get;set;}
        private List<ServiceCategroy> listCategories{get;set;}
        public IActionResult getServiceCategories()
        {
            listCategories = new List<ServiceCategroy>();
            con  = new dbConnection();
            com = new MySqlCommand("SELECT * FROM `servicecategories`",con.connection);
            reader = com.ExecuteReader();
            while(reader.Read())
            {
                categroy = new ServiceCategroy();  
                categroy.id = int.Parse(reader[0].ToString());
                categroy.name = reader[1].ToString();
                listCategories.Add(categroy);
            }
            return Ok(listCategories);
        }

        public IActionResult EdtitServiceProvider(ServiceProvider GetObj)
        {
            int userId = Convert.ToInt16(HttpContext.Session.GetString("userId"));
            byte[] img = Convert.FromBase64String(GetObj.img);
            string sqlInsert="";
            if(GetObj.serId!=0)
                sqlInsert = "UPDATE `serviceprovider` SET `imgType`=@imgType, `img`=@img, `about`=@about, `city`=@city, `cateId`=@cateId, `loaction`=@location WHERE `userId`=@userId";
            else 
                sqlInsert = "INSERT INTO `serviceprovider`(`userId`, `imgType`, `img`, `about`, `city`, `cateId`, `loaction`) VALUES (@userId,@imgType, @img, @about, @city, @cateId, @location)";
            con = new dbConnection();
            com = new MySqlCommand(sqlInsert,con.connection);
            com.Parameters.AddWithValue("userId",userId);
            com.Parameters.AddWithValue("imgType",GetObj.imgType);
            com.Parameters.AddWithValue("img",img);
            com.Parameters.AddWithValue("about",GetObj.about);
            com.Parameters.AddWithValue("city",GetObj.city);
            com.Parameters.AddWithValue("cateId",GetObj.cateId);
            com.Parameters.AddWithValue("location",GetObj.location); 
            com.ExecuteNonQuery();
            return Ok(1);
        }

    }
}

Views/ServiceProvider/EditService.cshtml
@{

}
   <div class="section-title-01 honmob">
            <div class="bg_parallax image_02_parallax"></div>
            <div class="opacy_bg_02">
                <div class="container">
                    <h1>Registeration</h1>
                    <div class="crumbs">
                        <ul>
                            <li><a href="index.php.html">Home</a></li>
                            <li>/</li>
                            <li>Registeration</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <section class="content-central">
            <div class="semiboxshadow text-center"></div>
            <div class="content_info">
                <div class="paddings-mini">
                    <div class="container">
                        <div class="col-xs-12 col-sm-6 col-md-6 col-md-offset-3 profile1" style="padding-bottom:40px;">
                            <div class="thinborder-ontop">
                                <h3>User Info</h3>
                                <form id="EditServiceProvider" onsubmit="return false">  
                                    <div class="form-group row">
                                        <label for="upload-file" class="col-md-4 col-form-label text-md-right">Name</label>
                                        <div class="col-md-6">
                                            <input type="file" class="form-control" id="upload-file" name="upload-file" value="" autofocus="">
                                            <div class="pro-img">
                                                <img src="~/serviceprovider/profile-image.png" id="view-img" width="100%" alt="">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="name" class="col-md-4 col-form-label text-md-right">About</label>
                                        <div class="col-md-6">
                                            <textarea name="about" id="about" class="form-control" required="" autofocus=""></textarea>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="city" class="col-md-4 col-form-label text-md-right">City</label>
                                        <div class="col-md-6">
                                            <input id="city" type="text" class="form-control" name="city" value="" required="">
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="userType"
                                            class="col-md-4 col-form-label text-md-right">Service Category</label>
                                        <div class="col-md-6">
                                            <select name="cateId" id="cateId" class="form-control">
                                                <option value="0" disabled selected>--Select Service Category--</option>
                                            </select>
                                        </div>    
                                    </div>
                                    <div class="form-group row">
                                        <label for="city" class="col-md-4 col-form-label text-md-right">Service Location</label>
                                        <div class="col-md-6">
                                            <input id="service-location" type="text" class="form-control" name="service-location" value="" required="">
                                        </div>
                                    </div>
                                    <div class="form-group row mb-0">
                                        <div class="col-md-10">
                                            <button type="submit" class="btn btn-primary pull-right update">update</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>  
            <div class="section-twitter">
                <i class="fa fa-twitter icon-big"></i>
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="text-center">
                            </div>
                        </div>
                    </div>
                </div>
            </div>             
        </section>

<script>
    $(document).ready(function(){
       // alert('ok');
        var img,imgs,userid=0;
        function ReadImage(input)
        {
            if(input.files && input.files[0])
            {
                var reader = new FileReader();
                reader.onload = function(e)
                {
                    img = e.target.result;
                    $('#view-img').attr('src',img);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
        $('#upload-file').change(function(){
            ReadImage(this);
        })
        fetchCategories();
        function fetchCategories()
        {
            $.ajax({
                url:'@Url.Action("getServiceCategories","ServiceProvider")',
                type:'get',
                dataType:'json',
                success:function(data)
                {
                    //console.log(data);
                    for(var i=0;i<data.length;i++)
                    {
                        $('#cateId').append(new Option(data[i].name,data[i].id));
                    }
                }
            })
        }

        $('#EditServiceProvider').on('submit',function(){
            if(img!=null) imgs = img.split(",");
            else
            {
                img = $('#view-img').attr('src');
                imgs = img.split(",");
            }
            var setObj = {
                'imgType':imgs[0], 'img':imgs[1],'about':$('#about').val(),
                'city':$('#city').val() ,'cateId':$('#cateId').val(), 'location':$('#service-location').val(),
                'serId':userid
            }
            $.ajax({
                url:'@Url.Action("EdtitServiceProvider","ServiceProvider")',
                type:'post',
                dataType:'json',
                data:{GetObj : setObj},
                success:function(data)
                {
                    window.location.replace('@Url.Action("ServiceProviderProfile","ServiceProvider")')
                    img = null;
                }
            })
        })
        getRow();
        function getRow()
        {
            $.ajax({
                url:'@Url.Action("GetProvider","ServiceProvider")',
                type:'post',
                dataType:'json',
                success:function(data)
                {
                    console.log(data);
                    $('#view-img').attr('src',data.img);
                    $('#about').val(data.about);
                    $('#cateId').val(data.cateId);
                    $('#service-location').val(data.location);
                    $('#city').val(data.city);
                    userid = data.serId;
                }
            })
        }
    });
</script>

Views/ServiceProvider/ServiceProviderProfile.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{
    ViewData["Title"]="Profile-page";
}
        <div class="section-title-01 honmob">
            <div class="bg_parallax image_02_parallax"></div>
            <div class="opacy_bg_02">
                <div class="container">
                    <h1>Profile</h1>
                    <div class="crumbs">
                        <ul>
                            <li><a href="index.php.html">Home</a></li>
                            <li>/</li>
                            <li>Profile</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <section class="content-central">
            <div class="content_info">
                <div class="paddings-mini">
                    <div class="container">
                        <div class="row portfolioContainer">
                            <div class="col-md-8 col-md-offset-2 profile1">
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <div class="row">
                                            <div class="col-md-6">
                                                Profile @ViewBag.msg
                                            </div>
                                            <div class="col-md-6" style="display: flex;justify-content: end;align-items: center;">
                                                <div class="alert"></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="panel-body">
                                        <div class="row">
                                            <div class="col-md-4">
                                                <img src="~/serviceprovider/profile-image.png" id="view_img" width="100%" alt="">
                                            </div>
                                            <div class="col-md-8">
                                                <h3>Name : @HttpContextAccessor.HttpContext.Session.GetString("name")</h3>
                                                <p id="about"></p>
                                                <p id="email"><b>Email</b> : @HttpContextAccessor.HttpContext.Session.GetString("email")</p>
                                                <p id="phone"><b>Phone</b> : @HttpContextAccessor.HttpContext.Session.GetString("phone");</p>
                                                <p ><b>Service Category</b> : <span id="catename"></span></p>
                                                <p ><b>Service Location</b> : <span id="location"></span></p>
                                            </div>
                                            <div class="form-group row mb-0">
                                                <div class="col-md-10">
                                                    <a asp-action="EditService" class="btn btn-primary pull-right update" asp-controller="ServiceProvider">Edit</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

<script>
    $(document).ready(function(){
        $.ajax({
            url:'@Url.Action("GetProvider","ServiceProvider")',
            type:'post',
            dataType:'json',
            success:function(data)
            {
                //console.log(data);
                $('#view_img').attr('src',data.img);
                $('#about').text(data.about);
                $('#catename').text(data.cateName);
                $('#location').text(data.location);
            }
        });
    });
</script>