Controllers/SliderController.cs
using System.Data;
using HomeService.Models;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using System;
using System.Collections.Generic;

namespace HomeService.Controllers
{
    public class SliderController:Controller
    {
        private MySqlCommand com {get;set;}
        private MySqlDataReader dataReader{get;set;}
        private DataTable dataTable{get;set;}
        private dbConnection dbCon{get;set;}
        private byte[] imgbyte;
        private SliderModel obj{get;set;}
        private List<SliderModel> listSlider;
        public IActionResult ViewSlider()
        {
            return View();
        }
        //add new slider
        public IActionResult addSlider(SliderModel getObj)
        {   
            if(getObj.img!=null)
                imgbyte = Convert.FromBase64String(getObj.img);
            dbCon = new dbConnection();
            com = new MySqlCommand("INSERT INTO `slider`(`title`, `status`, `imgType`, `img`, `date`) VALUES (@title,@status,@imgtype,@img,@date)",dbCon.connection);
            com.Parameters.AddWithValue("title",getObj.title);
            com.Parameters.AddWithValue("status",getObj.status);
            com.Parameters.AddWithValue("imgtype",getObj.imgType);
            com.Parameters.AddWithValue("img",imgbyte);
            com.Parameters.AddWithValue("date",DateTime.Now);
            if(com.ExecuteNonQuery()==1) return Ok(1);
            else return Ok(0);
        }
        //select all rows
        public IActionResult getRowFromDatabase()
        {
            dbCon = new dbConnection();
            listSlider = new List<SliderModel>();
            com = new MySqlCommand("SELECT * FROM `slider`",dbCon.connection);
            dataReader = com.ExecuteReader();
            while(dataReader.Read())
            {
                obj = new SliderModel();
                obj.id = int.Parse(dataReader[0].ToString());
                obj.title = dataReader[1].ToString();
                obj.status = dataReader[2].ToString();
                obj.img = dataReader[3].ToString()+","+Convert.ToBase64String((byte[])dataReader[4]);
                DateTime dateTime = Convert.ToDateTime(dataReader[5].ToString());
                obj.date = dateTime.ToString("MM-dd-yyyy");
                if(string.IsNullOrEmpty(dataReader[6].ToString()))
                {
                    obj.lastDate = "Null";
                }
                else
                {
                     DateTime lastDate = Convert.ToDateTime(dataReader[6].ToString());
                    obj.lastDate = lastDate.ToString("MM-dd-yyyy");
                }
               
                listSlider.Add(obj);
            }
            return Ok(listSlider);
        }
        //delete slide
        public IActionResult deleteRow(int get_id)
        {
            dbCon = new dbConnection();
            com = new MySqlCommand("DELETE FROM `slider` WHERE `id`="+get_id,dbCon.connection);
            com.ExecuteNonQuery();   
            return Ok(1);
        }
        //show record
        public IActionResult showRecord(int get_id)
        {
            dbCon = new dbConnection();
            com = new MySqlCommand("SELECT * FROM `slider` WHERE id="+get_id,dbCon.connection);
            dataReader = com.ExecuteReader();
            while(dataReader.Read())
            {
                obj = new SliderModel();
                obj.id = Convert.ToInt32(dataReader[0].ToString());
                obj.title = dataReader[1].ToString();
                obj.status = dataReader[2].ToString();
                obj.img = dataReader[3].ToString()+","+Convert.ToBase64String((byte[])dataReader[4]);
            }
            return Ok(obj);
        }

        //update
        public IActionResult updateRow(SliderModel get_obj,int get_id)
        {
            dbCon = new dbConnection();
            imgbyte = Convert.FromBase64String(get_obj.img);
            string MySqlQuery = "UPDATE slider SET title=@title , status=@status, imgType=@imgType, img=@img, date_edit=@date WHERE id=@id";
            com = new MySqlCommand(MySqlQuery,dbCon.connection);  
            com.Parameters.AddWithValue("id",get_id);
            com.Parameters.AddWithValue("title",get_obj.title);
            com.Parameters.AddWithValue("status",get_obj.status);
            com.Parameters.AddWithValue("imgType",get_obj.imgType);
            com.Parameters.AddWithValue("img",imgbyte);
            com.Parameters.AddWithValue("date",DateTime.Now);
            com.ExecuteNonQuery();
            return Ok(1);
        }
    }
}

Views/Slider/ViewSlider.cshtml
@{
    ViewData["Title"]="All-Slider";
}

<style>
    .fa-times{
        color: red;
        font-size: 20px;
    }
    .fa-edit{
        color: blue;
        font-size: 20px;
    }
</style>

       <div class="section-title-01 honmob">
            <div class="bg_parallax image_02_parallax"></div>
            <div class="opacy_bg_02">
                <div class="container">
                    <h1>All Service </h1>
                    <div class="crumbs">
                        <ul>
                            <li><a href="index.php.html">Home</a></li>
                            <li>/</li>
                            <li>All Service</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <section class="content-central">
            <div class="content_info">
                <div class="paddings-mini">
                    <div class="container">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-md-6">All Service Category</div>
                                    <div class="col-md-6" style="display: flex;justify-content: end;align-items: center;">
                                        <a data-toggle="modal" data-target="#modal_serive" class="btn btn-primary">Add Categories</a>
                                    </div>
                                </div>
                            </div>
                            <div class="panel-body table-responsive">
                                <table class="table table-striped" id="tblSlider" >
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Image</th>
                                            <th>Name</th>
                                            <th>Status</th>
                                            <th>Create At</th>
                                            <th>Last Edit</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                                 
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <div class="modal fade" id="modal_serive">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        Add New Slider
                        <a href="#" class="close" data-dismiss="modal">x</a>
                    </div>
                    <div class="modal-body">
                        <form id="form-add-slider" onsubmit="return false">
                            <div class="row" style="padding: 5px 20px;">
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="" class="form-control-label">Title</label>
                                        <input type="text" class="form-control" id="title" required>
                                    </div>
                                     <div class="form-group">
                                        <label for="" class="form-control-label">Status</label>
                                        <select name="status" id="status" class="form-control">
                                            <option value="" disabled selected>--select type of discount--</option>
                                            <option value="active">Active</option>
                                            <option value="Inactive">Inactive</option>
                                        </select>
                                    </div>
                               
                                    <div class="form-group">
                                        <label for="" class="form-control-label">Image</label>
                                        <input type="file" class="form-control" id="img-upload" required>
                                        <img src="" alt="" id="view-img" width="70px" class="my-3">
                                    </div>
                                </div>
                            
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-sm btn-danger btnClear">Clear</button>
                                    <button type="submit" class="btn btn-primary btn-sm">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                   
                </div>
            </div>
        </div>

         <div class="modal fade" id="modal_edit">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        Update Slider
                        <a href="#" class="close" data-dismiss="modal">x</a>
                    </div>
                    <div class="modal-body">
                        <form id="form-update-slider" onsubmit="return false">
                            <div class="row" style="padding: 5px 20px;">
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="" class="form-control-label">Title</label>
                                        <input type="text" class="form-control" id="utitle" required>
                                    </div>
                                     <div class="form-group">
                                        <label for="" class="form-control-label">Status</label>
                                        <select name="status" id="ustatus" class="form-control">
                                            <option value="" disabled selected>--select type of discount--</option>
                                            <option value="active">Active</option>
                                            <option value="Inactive">Inactive</option>
                                        </select>
                                    </div>
                               
                                    <div class="form-group">
                                        <label for="" class="form-control-label">Image</label>
                                        <input type="file" class="form-control" id="uimg-upload" >
                                        <img src="" alt="" id="uview-img" width="70px" class="my-3">
                                    </div>
                                </div>
                            
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-sm btn-danger btnClear">Clear</button>
                                    <button type="submit" class="btn btn-primary btn-sm">Save</button>
                                </div>
                            </div>
                        </form>
                    </div>
                   
                </div>
            </div>
        </div>


<script>
    $(document).ready(function(){
        var img,imgs,listSlider=[],id,datatable;
        datatable = $('#tblSlider').DataTable({
            data:listSlider,
            columns:[
                {data:'id',AutoWidth:true},
                {data:'img',AutoWidth:true,
                    'render':function(data)
                    {
                        return '<img src="'+data+'" alt="" width="80px" class="my-3">';
                    }
                },
                {data:'title',AutoWidth:true},
                {data:'status',AutoWidth:true},
                {data:'date',AutoWidth:true},
                {data:'lastDate',AutoWidth:true},
                {data:'id',AutoWidth:true,
                    'render':function(data)
                    {
                        var edit = '<a edit='+data+' class="btn btn-sm" id="btnEdit" data-toggle="modal" data-target="#modal_edit"><i class="fas fa-edit"></i></a>';
                        var del = '<a del='+data+' class="btn btn-sm" id="btndelete"><i class="fas fa-times"></i></a>'
                        return edit+" "+del;
                    }
                }
                
            ]
        });

        //function read image
        function imageReader(input,idimage)
        {
            if(input.files && input.files[0])
            {
                var reader = new FileReader();
                reader.onload = function(e)
                {
                    img = e.target.result;
                    $(idimage).attr('src',img);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
        //call function
        $('#img-upload').change(function(){
            imageReader(this,'#view-img');
        })
        $('#uimg-upload').change(function(){
            imageReader(this,'#uview-img');
        })
        //add 
        $('#form-add-slider').on('submit',function(){
            imgs = img.split(",");
            var setObj = {
                'title':$('#title').val(),'status':$('#status').val(),
                'imgType':imgs[0], 'img':imgs[1]
            };
            $.ajax({
                url:'@Url.Action("addSlider","Slider")',
                type:'post',
                dataType:'json',
                data:{getObj : setObj},
                success:function(data)
                {
                    swal('Save','data has been saved successfully.','success');
                    ReadRows();
                    img = null;
                }
            })
        })

        //
        ReadRows();
        function ReadRows()
        {
            $.ajax({
                url:'@Url.Action("getRowFromDatabase","Slider")',
                type:'get',
                dataType:'json',
                success:function(data)
                {
                    console.log(data);
                    listSlider=[];
                    listSlider=data;
                    datatable.clear();
                    datatable.rows.add(listSlider);
                    datatable.draw();
                }
            })
        }
        $(document).on('click','#btndelete',function(){
            var del = $(this).attr('del');
            //alert(del);
            swal({
                title:'Are you sure...?',
                text:'If you decided delete this data you can not recovery.',
                icon:'warning',
                buttons:true,
                dangerMode:true,
            })
            .then((willdelete)=>{
                if(willdelete)
                {
                     $.ajax({
                        url:'@Url.Action("deleteRow","Slider")',
                        type:'post',
                        dataType:'json',
                        data:{get_id : del},
                        success:function(data)
                        {
                            swal('Deleted','data has been deleted successfully.','success');
                            ReadRows();
                        }
                    })
                }
                else swal("Your data safe.");
            });
        });
        var edit;
        $(document).on('click','#btnEdit',function(){
            edit = $(this).attr('edit');
            //alert(edit);
            $.ajax({
                url:'@Url.Action("showRecord","Slider")',
                type:'post',
                dataType:'json',
                data:{get_id : edit},
                success:function(data)
                {
                   // console.log(data);
                    $('#utitle').val(data.title);
                    $('#ustatus').val(data.status);
                    $('#uview-img').attr('src',data.img);
                }
            })
        })

        //update row 
        $('#form-update-slider').on('submit',function(){
            if(img!=null) imgs = img.split(",");
            else
            {
                img = $('#uview-img').attr('src');
                imgs = img.split(",");
            }

            var obj = {
                'title': $('#utitle').val(), 'status': $('#ustatus').val(),
                'imgType': imgs[0] , 'img' : imgs[1]
            }

            $.ajax({
                url:'@Url.Action("updateRow","Slider")',
                type:'post',
                dataType:'json',
                data :{get_obj : obj ,get_id : edit},
                success: function(data)
                {
                    swal('Updated','your data has been updated.','success');
                    ReadRows();
                    img = null;
                }
            })
        });
        $(document).on('click','.btnClear',function(){
            $('.form-control').val('');
            $('#uview-img').attr('src','');
            $('#view-img').attr('src','');
        })
    });
</script>