Models/Contacts.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomeService
{
    public class Contacts
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string message { get; set; }
        public DateTime date { get; set; }
    }
}

Models/ServiceProvider.cs
namespace HomeService
{
    public class ServiceProvider
    {
        public int id { get; set; } 
        public int serId { get; set; }
        public string name { get; set; }
        public string imgType { get; set; }
        public string img { get; set; }
        public string email {get;set;}
        public string about { get; set; }
        public string phone{get;set;}
        public string city { get; set; }
        public int cateId { get; set; }
        public string cateName{get;set;}
        public string location { get; set; }

    }
}

Controllers/AdminManageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.AspNetCore.Mvc;

namespace HomeService.Controllers
{
    public class AdminManageController:Controller
    {
        ///dbConnection db = new dbConnection();
        ServiceCategroy service{get;set;}
        private string query{get;set;}
        private List<ServiceCategroy> listService{get;set;}
        private DataTable dTable = new DataTable();
        private int result=0;
        public IActionResult ViewService()
        {
            return View();
        }
        public IActionResult AddServiceCategory()
        {
            return View();
        }
        public IActionResult AllService()
        {
            return View();
        }
        public IActionResult Contact()
        {
            return View();
        }
        public IActionResult ServiceProvider()
        {
            return View();
        }
        //Add New Service Category
        public IActionResult AddNewServiceCategory(ServiceCategroy setData)
        {
            query="INSERT INTO servicecategories(name,slug,imgType,image,feather) VALUES(@name,@slug,@imgType,@img,@feather)";
            service = new ServiceCategroy();
            result = service.Modify(setData,query);
            return Ok(result);
        }
        //show all row on datatable
        public IActionResult GetServieFromDataBase()
        {
            service = new ServiceCategroy();
            listService = new List<ServiceCategroy>();
            query="SELECT * FROM servicecategories";
            dTable = service.ShowRows(query);
            foreach(DataRow row in dTable.Rows)
            {
                service = new ServiceCategroy();
                service.id = int.Parse(row[0].ToString());
                service.name = row[1].ToString();
                service.slug = row[2].ToString();
                service.img = row[3].ToString() +","+Convert.ToBase64String((byte[])row[4]);
                listService.Add(service);
            }
            return Ok(listService);
        }
        //Show row to form
        public IActionResult showRow(int setValue)
        {
            listService = new List<ServiceCategroy>();
            service = new ServiceCategroy();
            DataRow row = service.ShowRows("SELECT * FROM servicecategories WHERE id="+setValue).Rows[0];
            service.name=row[1].ToString();
            service.slug=row[2].ToString();
            service.img = row[3].ToString() +","+Convert.ToBase64String((byte[])row[4]);
            service.feather = row[5].ToString();
            listService.Add(service);
            return Ok(listService);
        }
        //upadate valuse
        public IActionResult updateRow(ServiceCategroy setData)
        {
            query="UPDATE servicecategories SET name=@name,slug=@slug,imgType=@imgType,image=@img,feather=@feather WHERE id="+setData.id;
            service = new ServiceCategroy();
            result = service.Modify(setData,query);
            return Ok(result);
        }
        //delete 
        public IActionResult DeletedRow(int delId)
        {
            service = new ServiceCategroy();
            result = service.DeleteService("DELETE FROM servicecategories WHERE id=@id",delId);
            return Ok(result);
        }
        //Fetch Category
        public IActionResult Categories()
        {
            service = new ServiceCategroy();
            listService = new List<ServiceCategroy>();
            query = "SELECT id,name FROM servicecategories";
            foreach(DataRow row in service.ShowRows(query).Rows)
            {
                service = new ServiceCategroy();
                service.id = int.Parse(row[0].ToString());
                service.name = row[1].ToString();
                listService.Add(service);
            }
            return Ok(listService);
        }

////////////////////////////////////////////////////////////////////////////////
////////////////////////////service section////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

        //Add new Service
        service objService{get;set;}
        List<service> ObjServiceList{get;set;}
        public IActionResult AddService(service getObj )
        {
            objService = new service();
            query = "INSERT INTO service_tbl(name, slug, tagline, service_cate_id, price,discount,discount_Type, imgType, img, description, inclusion, exclusion) VALUES(@name,@slug,@tage,@cid,@price,@discount,@disType,@imgType,@img,@des,@inc,@exc)";
            result = objService.ModifyService(getObj,query);
            return Ok(result);
        }
        //Show all row on view 
        public IActionResult ShowAllService()
        {
            service = new ServiceCategroy();
            ObjServiceList = new List<service>();
            query = "SELECT service_tbl.name,service_tbl.price,service_tbl.status,servicecategories.name,service_tbl.imgType,service_tbl.img,service_tbl.id FROM `service_tbl`,servicecategories WHERE service_tbl.service_cate_id=servicecategories.id";
            foreach(DataRow row in service.ShowRows(query).Rows)
            {
                objService = new service();
                objService.name = row[0].ToString();
                objService.price = decimal.Parse(row[1].ToString());
                objService.status = row[2].ToString();
                objService.categoryName = row[3].ToString();
                objService.img = row[4].ToString()+","+Convert.ToBase64String((byte[])row[5]);
                objService.id = int.Parse(row[6].ToString());
                ObjServiceList.Add(objService);
            }
            return Ok(ObjServiceList);
        }
        //delete service 
        public IActionResult DeleteService(service did)
        {
            //code here
            objService = new service();
            query = "DELETE FROM service_tbl WHERE id=@id";
            result = objService.ModifyService(did,query);
            return Ok(result);
        }
        //show single row 
        public IActionResult ShowSingRow(int getId)
        {
            service = new ServiceCategroy();
            query="SELECT name,slug,tagline,service_cate_id,price,imgType,img,description,inclusion,exclusion,status,discount,discount_Type FROM service_tbl WHERE id="+getId;
            DataRow row = service.ShowRows(query).Rows[0];
            objService = new service();
            objService.name = row[0].ToString();
            objService.slug = row[1].ToString();
            objService.tageline = row[2].ToString();
            objService.category = int.Parse(row[3].ToString());
            objService.price = decimal.Parse(row[4].ToString());
            objService.img = row[5].ToString()+","+Convert.ToBase64String((byte[])row[6]);
            objService.description = row[7].ToString();
            objService.inclusion = row[8].ToString();
            objService.exclusion = row[9].ToString();
            objService.status = row[10].ToString();
            objService.discount = decimal.Parse(row[11].ToString());
            objService.dis_Type = row[12].ToString();
            return Ok(objService);
        }

        //upadate service
        public IActionResult updateService(service getObj)
        {
            objService = new service();
            query = "UPDATE service_tbl SET name=@name, slug=@slug, tagline=@tage, service_cate_id=@cid, price=@price,discount=@discount,discount_Type=@disType, imgType=@imgType, img=@img, description=@des, inclusion=@inc, exclusion=@exc,status='"+getObj.status+"' WHERE id="+getObj.id;
            result = objService.ModifyService(getObj,query);
            return Ok(result);
        }
        //show all service provider user
        public IActionResult GetAllProvider()
        {
            List<ServiceProvider> listProvider = new List<ServiceProvider>();
            service = new ServiceCategroy();
            query = "SELECT s.id, s.imgType,s.img,u.name,u.email,u.phone,s.city,c.name,s.`loaction` FROM `serviceprovider` AS s,user AS u,servicecategories AS c WHERE s.userId = u.id AND s.cateId = c.id ORDER BY s.id DESC";
            DataTable table = new DataTable();
            table = service.ShowRows(query);
            foreach(DataRow row in table.Rows)
            {
                ServiceProvider provider = new ServiceProvider();
                provider.id = int.Parse(row[0].ToString());
                provider.img = row[1].ToString()+","+Convert.ToBase64String((byte[])row[2]);
                provider.name = row[3].ToString();
                provider.email = row[4].ToString();
                provider.phone = row[5].ToString();
                provider.city = row[6].ToString();
                provider.cateName = row[7].ToString();
                provider.location = row[8].ToString();
                listProvider.Add(provider);
            }
            return Ok(listProvider);
        }

    }
}

Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MySql.Data.MySqlClient;
using System.Data;

namespace HomeService.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult ViewContact()
        {
            return View();
        }

        private MySqlCommand com {get;set;}
        private dbConnection dbCon {get;set;}
        private MySqlDataAdapter data {get;set;}
        private DataTable table {get;set;}
        private Contacts contacts{get;set;}
        private List<Contacts> listcontact = new List<Contacts>();
        public IActionResult SendMessage(Contacts obj)
        {
            dbCon = new dbConnection();
            com = new MySqlCommand("INSERT INTO `contact`(`name`, `email`, `phone`,message, `sendDate`) VALUES (@name,@email,@phone,@message,@date)",dbCon.connection);
            com.Parameters.AddWithValue("name",obj.name);
            com.Parameters.AddWithValue("email",obj.email);
            com.Parameters.AddWithValue("phone",obj.phone);
            com.Parameters.AddWithValue("message",obj.message);
            com.Parameters.AddWithValue("date",DateTime.Now);
            com.ExecuteNonQuery();
            return Ok(1);
        }
        public IActionResult GetDataContact()
        {
            dbCon = new dbConnection();
            data = new MySqlDataAdapter("SELECT * FROM `contact`",dbCon.connection);
            table = new DataTable();
            data.Fill(table);
            foreach(DataRow row in table.Rows)
            {
                contacts = new Contacts();
                contacts.id = int.Parse(row[0].ToString());
                contacts.name = row[1].ToString();
                contacts.email = row[2].ToString();
                contacts.phone = row[3].ToString();
                contacts.message = row[4].ToString();
                contacts.date = Convert.ToDateTime(row[5].ToString());
                listcontact.Add(contacts);
            }
            return Ok(listcontact);
        }
    }
}

Controllers/ServiceProviderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;

namespace HomeService.Controllers
{
    public class ServiceProviderController:Controller
    {
        private MySqlCommand com {get;set;}
        private MySqlDataReader reader{get;set;}
        private MySqlDataAdapter dataAdapter{get;set;}
        private dbConnection con {get;set;}
        private ServiceProvider provider {get;set;}
        public IActionResult ServiceProviderDashbaord()
        {
            return View();
        }
        public IActionResult ServiceProviderProfile()
        {
            //GetProvider();
            return View();
        }

        public IActionResult EditService()
        {
            return View();
        }
        //SELECT serviceprovider.imgType,serviceprovider.img,serviceprovider.about,serviceprovider.city,servicecategories.name,serviceprovider.loaction,serviceprovider.userId FROM `serviceprovider`,servicecategories WHERE serviceprovider.cateId = servicecategories.id AND serviceprovider.userId = "+userId
        public IActionResult GetProvider()
        {
            try
            {
                int userId = Convert.ToInt16(HttpContext.Session.GetString("userId"));
                con = new dbConnection();
                string sqlQuery = "SELECT serviceprovider.imgType,serviceprovider.img,serviceprovider.about,serviceprovider.city,servicecategories.name,serviceprovider.loaction,serviceprovider.userId,servicecategories.id FROM `serviceprovider`,servicecategories WHERE serviceprovider.cateId = servicecategories.id AND serviceprovider.userId = "+userId;
                dataAdapter = new MySqlDataAdapter(sqlQuery,con.connection);
                DataTable data = new DataTable();
                dataAdapter.Fill(data);
                provider = new ServiceProvider();
                DataRow row = data.Rows[0];
                provider.img = row[0].ToString()+","+Convert.ToBase64String((byte[])row[1]);
                provider.about = row[2].ToString();
                provider.city = row[3].ToString();
                provider.cateName = row[4].ToString();
                provider.location = row[5].ToString();
                provider.serId = int.Parse(row[6].ToString());
                provider.cateId = int.Parse(row[7].ToString());
                
            }
            catch(Exception ex){throw(ex);}
            return Ok(provider);
        }
        private ServiceCategroy categroy{get;set;}
        private List<ServiceCategroy> listCategories{get;set;}
        public IActionResult getServiceCategories()
        {
            listCategories = new List<ServiceCategroy>();
            con  = new dbConnection();
            com = new MySqlCommand("SELECT * FROM `servicecategories`",con.connection);
            reader = com.ExecuteReader();
            while(reader.Read())
            {
                categroy = new ServiceCategroy();  
                categroy.id = int.Parse(reader[0].ToString());
                categroy.name = reader[1].ToString();
                listCategories.Add(categroy);
            }
            return Ok(listCategories);
        }

        public IActionResult EdtitServiceProvider(ServiceProvider GetObj)
        {
            int userId = Convert.ToInt16(HttpContext.Session.GetString("userId"));
            byte[] img = Convert.FromBase64String(GetObj.img);
            string sqlInsert="";
            if(GetObj.serId!=0)
                sqlInsert = "UPDATE `serviceprovider` SET `imgType`=@imgType, `img`=@img, `about`=@about, `city`=@city, `cateId`=@cateId, `loaction`=@location WHERE `userId`=@userId";
            else 
                sqlInsert = "INSERT INTO `serviceprovider`(`userId`, `imgType`, `img`, `about`, `city`, `cateId`, `loaction`) VALUES (@userId,@imgType, @img, @about, @city, @cateId, @location)";
            con = new dbConnection();
            com = new MySqlCommand(sqlInsert,con.connection);
            com.Parameters.AddWithValue("userId",userId);
            com.Parameters.AddWithValue("imgType",GetObj.imgType);
            com.Parameters.AddWithValue("img",img);
            com.Parameters.AddWithValue("about",GetObj.about);
            com.Parameters.AddWithValue("city",GetObj.city);
            com.Parameters.AddWithValue("cateId",GetObj.cateId);
            com.Parameters.AddWithValue("location",GetObj.location); 
            com.ExecuteNonQuery();
            return Ok(1);
        }

    }
}

Views/AdminManage/AddServiceCategory.cshtml
@{
    ViewData["Title"]="Add-Service-page";
}
        <div class="section-title-01 honmob">
            <div class="bg_parallax image_02_parallax"></div>
            <div class="opacy_bg_02">
                <div class="container">
                    <h1>Admin Service Categories</h1>
                    <div class="crumbs">
                        <ul>
                            <li><a href="index.php.html">Home</a></li>
                            <li>/</li>
                            <li>Admin Service Categories</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <section class="content-central">
            <div class="content_info">
                <div class="paddings-mini">
                    <div class="container">
                        <div class="row portfolioContainer">
                            <div class="col-md-8 col-md-offset-2 profile1">
                                <div class="panel panel-default">
                                    <div class="panel-heading">
                                        <div class="row">
                                            <div class="col-md-6">
                                                Add New Service Carpentry
                                            </div>
                                            <div class="col-md-6" style="display: flex;justify-content: end;align-items: center;">
                                                <a asp-controller="AdminManage" asp-action="ViewService" class="btn btn-primary">All Categories</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="panel-body">
                                        <form action="" class="form-horizontal" id="AddServiceCategroy" onsubmit="return false">
                                            <div class="form-group row">
                                                <div class="col-sm-3">
                                                    <label for="name" class="form-control-label">Carpentry Name :</label>
                                                </div>
                                                <div class="col-sm-9">
                                                    <input type="text" class="form-control" id="name">
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <div class="col-sm-3">
                                                    <label for="name" class="form-control-label">Carpentry Slug :</label>
                                                </div>
                                                <div class="col-sm-9">
                                                    <input type="text" class="form-control" id="slug">
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <div class="col-sm-3">
                                                    <label for="name" class="form-control-label">Carpentry image :</label>
                                                </div>
                                                <div class="col-sm-9">
                                                    <input type="file" class="form-control" id="img_upload">
                                                    <img src="" id="view-img" alt="" width="70px">
                                                </div>
                                                
                                            </div>
                                            <button type="submit" class="btn btn-primary">Save</button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

<script>
    $(document).ready(function(){
        var img;
        function Readimage(input)
        {
            if(input.files && input.files[0])
            {
                var reader = new FileReader();
                reader.onload = function(e)
                {
                    img = e.target.result;
                    $('#view-img').attr('src',img);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }
        $('#img_upload').change(function(){
            Readimage(this);
        })

        $('#AddServiceCategroy').on('submit',function(){
            var imgs;
            if(img!=null) imgs = img.split(",");
            var obj = {
                'name':$('#name').val(),
                'slug':$('#slug').val(),
                'imgType':imgs[0],
                'img':imgs[1]
            }
            $.ajax({
                url:'@Url.Action("AddNewServiceCategory","AdminManage")',
                type:'POST',
                dataType:'JSON',
                data:{setData : obj},
                success:function(data)
                {
                    if(data==1) swal('Save','Data has been save successfylly.','success');
                    else swal('Warning','Sorry..!,Something is wrong.please check and try again.','warning');
                }
            })
        })
        
    })
</script>

Views/AdminManage/Contact.cshtml
@{
    ViewData["Title"]="Admin Contact page";
}
<style>
    .fa-edit{
        font-size: 20px;
        color: blue;
    }
    .fa-times{
        font-size: 20px;
        color: red;
    }
</style>
        <div class="section-title-01 honmob">
            <div class="bg_parallax image_02_parallax"></div>
            <div class="opacy_bg_02">
                <div class="container">
                    <h1>Contact Info</h1>
                    <div class="crumbs">
                        <ul>
                            <li><a href="index.php.html">Home</a></li>
                            <li>/</li>
                            <li>Contact Info</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <section class="content-central">
            <div class="content_info">
                <div class="paddings-mini">
                    <div class="container">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-md-6"><h3>List Contact</h3></div>
                                    <div class="col-md-6" style="display: flex;justify-content: end;align-items: center;">
                                        
                                    </div>
                                </div>
                            </div>
                            <div class="panel-body">
                                <table class="table table-striped" id="contact" >
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Name</th>
                                            <th>Email</th>
                                            <th>Phone</th>
                                            <th>Message</th>
                                            <th>Create_at</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                                 
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    <script>
        $(document).ready(function(){
            var table,ListContact=[];
            table = $('#contact').DataTable({
                data:ListContact,
                columns:[
                    {data:'id',autoWidth:true},
                    {data:'name',autoWidth:true},
                    {data:'email',autoWidth:true},
                    {data:'phone',autoWidth:true},
                    {data:'message',autoWidth:true},
                    {data:'date',autoWidth:true}
                ]
            });

            //get data function
            getContact();
            function getContact()
            {
                $.ajax({
                    url:'@Url.Action("GetDataContact","Contact")',
                    type:'get',
                    dataType:'json',
                    success:function(data)
                    {
                        console.log(data);
                        ListContact=[];
                        ListContact=data;
                        table.clear();
                        table.rows.add(ListContact);
                        table.draw();
                    }
                });
            }
        });
    </script>

Views/AdminManage/ServiceProvider.cshtml
@{
    ViewData["Title"]="Service Provider page";
}
<style>
    .fa-edit{
        font-size: 20px;
        color: blue;
    }
    .fa-times{
        font-size: 20px;
        color: red;
    }
</style>
        <div class="section-title-01 honmob">
            <div class="bg_parallax image_02_parallax"></div>
            <div class="opacy_bg_02">
                <div class="container">
                    <h1>Service Provider Info</h1>
                    <div class="crumbs">
                        <ul>
                            <li><a href="index.php.html">Home</a></li>
                            <li>/</li>
                            <li>Service Provider Info</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <section class="content-central">
            <div class="content_info">
                <div class="paddings-mini">
                    <div class="container">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-md-6"><h3>List Service Provider</h3></div>
                                    <div class="col-md-6" style="display: flex;justify-content: end;align-items: center;">
                                        
                                    </div>
                                </div>
                            </div>
                            <div class="panel-body">
                                <table class="table table-striped" id="ServiceProvider" >
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Image</th>
                                            <th>Name</th>
                                            <th>Email</th>
                                            <th>Phone</th>
                                            <th>City</th>
                                            <th>Service Category</th>
                                            <th>Service location</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                                 
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <img src="" width="80px" alt="">

    <script>
        $(document).ready(function(){
            var table,ListProvider=[];
            table = $('#ServiceProvider').DataTable({
                data:ListProvider,
                columns:[
                    {data:'id',autoWidth:true},
                    {data:'img',autoWidth:true,
                        'render':function(data){
                            return '<img src="'+data+'" width="80px" alt="">';
                        }
                    },
                    {data:'name',autoWidth:true},
                    {data:'email',autoWidth:true},
                    {data:'phone',autoWidth:true},
                    {data:'city',autoWidth:true},
                    {data:'cateName',autoWidth:true},
                    {data:'location',autoWidth:true}
                ]
            });

            //get data function
            getContact();
            function getContact()
            {
                $.ajax({
                    url:'@Url.Action("GetAllProvider","AdminManage")',
                    type:'get',
                    dataType:'json',
                    success:function(data)
                    {
                        console.log(data);
                        ListProvider=[];
                        ListProvider=data;
                        table.clear();
                        table.rows.add(ListProvider);
                        table.draw();
                    }
                });
            }
        });
    </script>