Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using HomeService.Models;
using System.Data;
using MySql.Data.MySqlClient;

namespace HomeService.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        
        public IActionResult Index()
        {
            ViewBag.Categories = HomeCategory();
            ViewBag.HomeService = ListOfServiceHomePage();
            ViewBag.CategoriesbyFeather = ListCategories();
            ViewBag.service8Home = ListOfService8();
            ViewBag.Slider = Slider();
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }
        public IActionResult Faq()
        {
            return View();
        }
        public IActionResult TermsOfUser()
        {
            return View();
        }
        ServiceCategroy service;
        List<ServiceCategroy> listService ;
        public string query{get;set;}
        private List<ServiceCategroy> HomeCategory()
        {
            service = new ServiceCategroy();
            listService = new List<ServiceCategroy>();
            query="SELECT * FROM servicecategories";
            foreach(DataRow row in service.ShowRows(query).Rows)
            {
                service = new ServiceCategroy();
                service.id = int.Parse(row[0].ToString());
                service.name = row[1].ToString();
                service.slug = row[2].ToString();
                service.img = row[3].ToString() +","+Convert.ToBase64String((byte[])row[4]);
                listService.Add(service);
            }
            return listService;
        }
        private service serviceObj ;
        private List<service> listServiceObj;
        private List<service> ListOfServiceHomePage()
        {
            listServiceObj = new List<service>();
            query="SELECT id, name,tagline,price,imgType,img FROM service_tbl WHERE status='yes'";
            foreach(DataRow row in service.ShowRows(query).Rows)
            {
                serviceObj = new service();
                serviceObj.id = int.Parse(row[0].ToString());
                serviceObj.name = row[1].ToString();
                serviceObj.tageline = row[2].ToString();
                serviceObj.price = decimal.Parse(row[3].ToString());
                serviceObj.img = row[4].ToString() +","+Convert.ToBase64String((byte[])row[5]);
                listServiceObj.Add(serviceObj);
            }
            return listServiceObj;
        }
        private List<service> ListOfService8()
        {
            listServiceObj = new List<service>();
            query="SELECT id, name,tagline,price,imgType,img FROM service_tbl WHERE status='yes' LIMIT 8";
            foreach(DataRow row in service.ShowRows(query).Rows)
            {
                serviceObj = new service();
                serviceObj.id = int.Parse(row[0].ToString());
                serviceObj.name = row[1].ToString();
                serviceObj.tageline = row[2].ToString();
                serviceObj.price = decimal.Parse(row[3].ToString());
                serviceObj.img = row[4].ToString() +","+Convert.ToBase64String((byte[])row[5]);
                listServiceObj.Add(serviceObj);
            }
            return listServiceObj;
        }

        private List<ServiceCategroy> ListCategories()
        {
            service = new ServiceCategroy();
            listService = new List<ServiceCategroy>();
            foreach(DataRow row in service.ShowRows("SELECT * FROM servicecategories WHERE feather='Yes' LIMIT 8").Rows)
            {
                service = new ServiceCategroy();
                service.id = int.Parse(row[0].ToString());
                service.name = row[1].ToString();
                service.img = row[3].ToString() +","+Convert.ToBase64String((byte[])row[4]);
                listService.Add(service);
            }

            return listService;
        }

        public IActionResult AutoComplete(string search)
        {
            listServiceObj = new List<service>();
            dbConnection con = new dbConnection();
            query = "SELECT id,name FROM `service_tbl` WHERE name LIKE '%"+search+"%'";
            MySqlDataAdapter data = new MySqlDataAdapter(query,con.connection);
            DataTable dt  = new DataTable();
            data.Fill(dt);
            foreach (DataRow row in dt.Rows)
            {
                listServiceObj.Add(new service{id=int.Parse(row[0].ToString()),name=row[1].ToString()});
            }
            return Ok(listServiceObj);
        }
        //slider
        private SliderModel slider{get;set;}
        private List<SliderModel> listSlider = new List<SliderModel>();
        public List<SliderModel> Slider()
        {
            service = new ServiceCategroy();
            DataTable dt = new DataTable();
            dt = service.ShowRows("SELECT `title`,`imgType`,`img` FROM `slider` WHERE `status`='active'");
            foreach(DataRow row in dt.Rows)
            {
                slider = new SliderModel();
                slider.title = row[0].ToString();
                slider.img = row[1].ToString()+","+Convert.ToBase64String((byte[])row[2]);
                listSlider.Add(slider);

            }
            return listSlider;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using Microsoft.AspNetCore.Mvc;

namespace HomeService.Controllers
{
    public class ServiceController:Controller
    {
        //dbConnection db = new dbConnection();
        private string query{get;set;}
        List<ServiceCategroy> serviceList = new List<ServiceCategroy>();
        ServiceCategroy service ;
        service objservice ;
        List<service> listService = new List<service>();
        public IActionResult ServiceCategory()
        {
            ServiceCategroy();
            return View();
        }
        
        [Route("ServiecByCategories/{id}")]
        public IActionResult ServiecByCategories(int id)
        {
            ServiceByCategory(id);
            return View();
        }
        public IActionResult ServiceCategroy()
        {
            query = "SELECT * FROM servicecategories";
            service = new ServiceCategroy();
            foreach(DataRow row in service.ShowRows(query).Rows)
            {
                service = new ServiceCategroy();
                service.id = int.Parse(row[0].ToString());
                service.name = row[1].ToString();
                service.slug = row[2].ToString();
                service.img = row[3].ToString()+","+Convert.ToBase64String((byte[])row[4]);
                serviceList.Add(service);
            }
            return View(serviceList);
        }
        public IActionResult ServiceByCategory(int cate_Id)
        {
            service = new ServiceCategroy();
            query = "SELECT id, name,tagline,price,imgType,img FROM service_tbl WHERE service_cate_id="+cate_Id;
            foreach(DataRow row in service.ShowRows(query).Rows)
            {
                objservice = new service();
                objservice.id = int.Parse(row[0].ToString());
                objservice.name = row[1].ToString();
                objservice.tageline = row[2].ToString();
                objservice.price = decimal.Parse(row[3].ToString());
                objservice.img = row[4].ToString()+","+Convert.ToBase64String((byte[])row[5]);
                listService.Add(objservice);
            }
            ViewBag.ListData = listService;

            service = new ServiceCategroy();
            DataRow dr = service.ShowRows("SELECT name FROM servicecategories WHERE id="+cate_Id).Rows[0];
            ViewBag.Category = dr[0].ToString();
            return View();
        }

        //------------------------------------------------------------------------///
        //[HttpPost]
        [Route("serviceDetail")]
        public IActionResult ServiceDetail(string name)
        {
            service = new ServiceCategroy();
            objservice = new service();
            query="SELECT name,slug,tagline,service_cate_id,price,imgType,img,description,inclusion,exclusion,status,discount,discount_Type FROM service_tbl WHERE name='"+name+"'";
            DataRow row = service.ShowRows(query).Rows[0];
            objservice = new service();
            objservice.name = row[0].ToString();
            objservice.slug = row[1].ToString();
            objservice.tageline = row[2].ToString();
            objservice.category = int.Parse(row[3].ToString());
            objservice.price = decimal.Parse(row[4].ToString());
            objservice.img = row[5].ToString()+","+Convert.ToBase64String((byte[])row[6]);
            objservice.description = row[7].ToString();
            objservice.inclusion = row[8].ToString();
            objservice.exclusion = row[9].ToString();
            objservice.status = row[10].ToString();
            objservice.discount = decimal.Parse(row[11].ToString());
            objservice.dis_Type = row[12].ToString();
            ViewBag.Total = objservice.price - objservice.discount;
            ViewBag.obj = objservice;
            
            return View();
        }
        
    }
}

Views/Home/Faq.cshtml
@{
    ViewData["Title"]="View-Faq";
}
<div class="section-title-01 honmob">
            <div class="bg_parallax image_02_parallax"></div>
            <div class="opacy_bg_02">
                <div class="container">
                    <h1>FAQ Questions</h1>
                    <div class="crumbs">
                        <ul>
                            <li><a href="index.html">Home</a></li>
                            <li>/</li>
                            <li>FAQ Questions</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <section class="content-central">
            <div class="semiboxshadow text-center">
                <img src="img/img-theme/shp.png" class="img-responsive" alt="">
            </div>
            <div class="content_info">
                <div class="container">
                    <div class="row" style="margin-top: -30px;">
                        <div class="titles">
                            <h2>FAQ <span>Questions</span></h2>
                            <i class="fa fa-plane"></i>
                            <hr class="tall">
                        </div>
                    </div>
                </div>
                <div class="container" style="margin-top: -70px;">
                    <div class="row padding-bottom">
                        <div class="col-md-12">
                            <div class="accrodation">
                                <span class="acc-trigger"><a href="#">Mision</a></span>
                                <div class="acc-container">
                                    <div class="content ptext">
                                        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac
                                            turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget,
                                            tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean
                                            ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est
                                            et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed,
                                            commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt
                                            condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui.
                                            Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus,
                                            neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna
                                            eros eu erat. Aliquam erat volutpat.</p>
                                    </div>
                                </div>
                                <span class="acc-trigger active"><a href="#">Vision</a></span>
                                <div class="acc-container">
                                    <div class="content ptext">
                                        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac
                                            turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget,
                                            tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean
                                            ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est
                                            et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed,
                                            commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt
                                            condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui.
                                            Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus,
                                            neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna
                                            eros eu erat. Aliquam erat volutpat.</p>
                                    </div>
                                </div>
                                <span class="acc-trigger"><a href="#">What we offer?</a></span>
                                <div class="acc-container">
                                    <div class="content ptext">
                                        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac
                                            turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget,
                                            tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean
                                            ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est
                                            et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed,
                                            commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt
                                            condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui.
                                            Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus,
                                            neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna
                                            eros eu erat. Aliquam erat volutpat.</p>
                                    </div>
                                </div>
                                <span class="acc-trigger"><a href="#">Our services</a></span>
                                <div class="acc-container">
                                    <div class="content ptext">
                                        Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac
                                        turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor
                                        sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies
                                        mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien
                                        ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae,
                                        ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros
                                        ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis
                                        pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor
                                        neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat.
                                    </div>
                                </div>
                                <span class="acc-trigger"><a href="#">Features</a></span>
                                <div class="acc-container">
                                    <div class="content ptext">
                                        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac
                                            turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget,
                                            tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean
                                            ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est
                                            et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed,
                                            commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt
                                            condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui.
                                            Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus,
                                            neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna
                                            eros eu erat. Aliquam erat volutpat.</p>
                                    </div>
                                </div>
                                <span class="acc-trigger"><a href="#">Product Sales</a></span>
                                <div class="acc-container">
                                    <div class="content ptext">
                                        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac
                                            turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget,
                                            tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean
                                            ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est
                                            et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed,
                                            commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt
                                            condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui.
                                            Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus,
                                            neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna
                                            eros eu erat. Aliquam erat volutpat.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content_info">
                <div class="skin_base paddings-mini color-white text-center">
                    <h2>Need Help? Call our Expert 24 X 7 - +91-1234567890</h2>
                </div>
            </div>            
        </section>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

        <section class="tp-banner-container">
            <div class="tp-banner">
                <ul>
                    @if(ViewBag.Slider.Count>0)
                    {
                        foreach (var item in ViewBag.Slider)
                        {
                        <li data-transition="slidevertical" data-slotamount="1" data-masterspeed="1000"
                            data-saveperformance="off" data-title="Slide">
                            <img src="@item.img" alt="@item.title" data-bgposition="center center"
                                data-kenburns="on" data-duration="6000" data-ease="Linear.easeNone" data-bgfit="130"
                                data-bgfitend="100" data-bgpositionend="right center">
                        </li>
                        }
                    }
                    else
                    {
                    <li data-transition="slidevertical" data-slotamount="1" data-masterspeed="1000"
                        data-saveperformance="off" data-title="Slide">
                        <img src="~/assets/img/slide/1.jpg" alt="fullslide1" data-bgposition="center center"
                            data-kenburns="on" data-duration="6000" data-ease="Linear.easeNone" data-bgfit="130"
                            data-bgfitend="100" data-bgpositionend="right center">
                    </li>
                    <li data-transition="slidehorizontal" data-slotamount="1" data-masterspeed="1000"
                        data-saveperformance="off" data-title="Slide">
                        <img src="~/assets/img/slide/2.jpg" alt="fullslide1" data-bgposition="top center"
                            data-kenburns="on" data-duration="6000" data-ease="Linear.easeNone" data-bgfit="130"
                            data-bgfitend="100" data-bgpositionend="right center">
                    </li>
                    }
                    
                </ul>
                <div class="tp-bannertimer"></div>
            </div>
            <div class="filter-title">
                <div class="title-header">
                    <h2 style="color:#fff;">BOOK A SERVICE</h2>
                    <p class="lead">Book a service at very affordable price, </p>
                </div>
                <div class="filter-header">
                    
                    @using (Html.BeginForm("serviceDetail","Service",FormMethod.Post))
                    {
                        <input type="text" id="search" name="name" required="required" placeholder="What Services do you want?"
                            class="input-large typeahead" autocomplete="off">
                        <input type="submit" id="submit" value="Searchs">
                    }
                </div>
            </div>
        </section>
        <section class="content-central">
            <div class="content_info content_resalt">
                <div class="container" style="margin-top: 40px;">
                    <div class="row">
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <ul id="sponsors" class="tooltip-hover">
                                @foreach (var item in ViewBag.Categories)
                                {
                                    <li data-toggle="tooltip" title="@item.name" data-original-title="AC"> <a
                                        asp-route-id="@item.id" asp-controller="Service" asp-action="ServiecByCategories"><img src="@item.img"
                                            alt="@item.name"></a></li>
                                }
                               
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="semiboxshadow text-center">
                <img src="assets/img/img-theme/shp.png" class="img-responsive" alt="">
            </div>
            <div class="content_info">
                <div>
                    <div class="container">
                        <div class="row">
                            <div class="titles">
                                <h2>SurfsideMedia <span>Choice</span> of Services</h2>
                                <i class="fa fa-plane"></i>
                                <hr class="tall">
                            </div>
                        </div>
                        <div class="portfolioContainer" style="margin-top: -50px;">
                            @if(ViewBag.HomeService.Count>0)
                            {
                            @foreach (var item in ViewBag.HomeService)
                            {
                            <div class="col-xs-6 col-sm-4 col-md-3 hsgrids"
                                style="padding-right: 5px;padding-left: 5px;">
                                <a class="g-list" asp-route-name="@item.name" asp-controller="Service" asp-action="serviceDetail">
                                    <div class="img-hover">
                                        <img src="@item.img" alt="@item.name Servicing"
                                            class="img-responsive">
                                    </div>
                                    <div class="info-gallery">
                                        <h3>@item.name Servicing</h3>
                                        <hr class="separator">
                                        <p>@item.name Servicing</p>
                                        <div class="content-btn"><a asp-route-name="@item.name" asp-controller="Service" asp-action="serviceDetail"
                                                class="btn btn-primary">Book Now</a></div>
                                        <div class="price"><span>&#36;</span><b>From</b>@item.price</div>
                                    </div>
                                </a>
                            </div> 
                            }}
                            else
                            {
                            <div class="col-12 hsgrids">
                                <div class="alert alert-danger text-center">
                                    Data not found here
                                </div>
                            </div>
                            }
                            
                        </div>
                    </div>
                </div>
            </div>
            <div class="content_info">
                <div class="bg-dark color-white border-top">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-4 ">
                                <div class="services-lines-info">
                                    <h2>WELCOME TO DIVERSIFIED</h2>
                                    <p class="lead">
                                        Book best services at one place.
                                        <span class="line"></span>
                                    </p>

                                    <p>Find a wide variety of home services.</p>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <ul class="services-lines">
                                    @foreach (var item in ViewBag.CategoriesbyFeather)
                                    {
                                    <li>
                                        <a asp-route-id="@item.id" asp-controller="Service" asp-action="ServiecByCategories">
                                            <div class="item-service-line">
                                                <i class="fa"><img class="icon-img"
                                                        src="@item.img"></i>
                                                <h5>@item.name</h5>
                                            </div>
                                        </a>
                                    </li>
                                    }
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <div class="container">
                    <div class="row">
                        <div class="titles">
                            <h2><span>Appliance</span>Services</h2>
                            <i class="fa fa-plane"></i>
                            <hr class="tall">
                        </div>
                    </div>
                </div>
                <div id="boxes-carousel">
                    @foreach (var item in ViewBag.service8Home)
                    {
                    <div>
                        <a class="g-list" asp-route-name="@item.name" asp-controller="Service" asp-action="serviceDetail">
                            <div class="img-hover">
                                <img src="@item.img" alt="" class="img-responsive">
                            </div>

                            <div class="info-gallery">
                                <h3>@item.name</h3>
                                <hr class="separator">
                                <p>@item.name</p>
                                <div class="content-btn"><a asp-route-name="@item.name" asp-controller="Service" asp-action="serviceDetail"
                                        class="btn btn-primary">Book Now</a></div>
                                <div class="price"><span>&#36;</span><b>From</b>@item.price</div>
                            </div>
                        </a>
                    </div>
                    }
                </div>
            </div>
        </section>

        <script>
            $(document).ready(function(){
                $('#search').autocomplete({
                    source: function(request,response)
                    {
                        $.ajax({
                            url:'@Url.Action("AutoComplete","Home")',
                            type:'post',
                            dataType:'json',
                            data:{search : $('#search').val()},
                            success:function(data)
                            {
                                //console.log(data);
                                response($.map(data,function(item){
                                    return {label:item.name,value:item.name};
                                }))
                            },
                            error:function(xhr, status,error)
                            {
                                alert('error');
                            }
                        })
                    }
                })
            });
        </script>
        